### ISSUE TITLE
Mixamo to UE4

### ISSUE THREAD

**Issue by Irishko1** [vespero-group/chiro-ue4#15]
Hello!

Was trying to rig a mixamo doll with this amazing addon and found that Reskin Mixamo to ue4 not working as it did before
not sure what it is - mixamo rig changed or issue in blender 2.91, or I'm doing something wrong

File with the issue on google drive 
https://drive.google.com/file/d/1musobGdX5HE0JRdP513lt-W9XFWd75sF/view?usp=sharing

_Armature -> Chiro (UE4) ->_ inactive 
![mixamo](https://user-images.githubusercontent.com/76467409/102857063-a50af100-448c-11eb-9372-daffa76517c8.png)

**Comment by dnsl48** [comment]
Thanks for reporting that!
Didn't check this yet, but my first bet would be the skeleton of this model may be incompatible.
We may need to add support for it.

**Comment by thunderpwn** [comment]
that would be great! thumbs up

**Comment by dnsl48** [comment]
Hi @thunderpwn, thanks for your interest in this addon!
Could you please tell us which Mixamo skeleton you've had issues with?

**Comment by dnsl48** [comment]
Thank you for reporting the issue!
This particular mixamo skeleton should work in the release 0.1.3
