### ISSUE TITLE
Can't export in latest release

### ISSUE THREAD

**Issue by sibo7851** [vespero-group/chiro-ue4#16]
Hi there, this plugin is exactly what I need, it doesn't seem to be working completely perfectly however, and in the current release the export option is totally greyed out even after fully following instructions in docs.

**Comment by dnsl48** [comment]
Hi! Thanks for reporting the issue!
Could you please clarify what exact release you have?

Grayed out export might happen if you didn't save your `.blend` file onto the hard drive. Could you please check if it's saved correctly (e.g. blender has the write access to the disk and the file is there in the target folder).

**Comment by dnsl48** [comment]
Hi @sibo7851, just wanted to follow up on that.

Could you please confirm that you still have that issue when the `.blend` file is saved on the hard drive and give me the versions of your `Blender` installation and `Chiro UE4` addon?

**Comment by dnsl48** [comment]
Ok, I'm closing it for now. If you still have the issue after saving the `.blend` file, please reopen this :)
