### ISSUE TITLE
Method to throw you two a couple of bucks!

### ISSUE THREAD

**Issue by mikeseese** [vespero-group/chiro-ue4#2]
Thank you for this! Chiro UE4 saved me so much time trying to learn rigging from scratch. Not only was it easy to follow and got me running, it also helped me, an all-things-3D-modeling novice, breach the subject and learn lots along the way.

I'd love to buy you both a beer/coffee/etc as a small token of my appreciation 🍻

**Comment by dnsl48** [comment]
Thank you very much for your kind words! This is very nice to hear the project is helping people. That alone is already excellent motivation for us to do more :)
Nonetheless, we love beer and coffee too, so I'll try to figure out some options to donate for the project cause :+1:

**Comment by dnsl48** [comment]
@seesemichaelj if you still want to buy us coffee, the docs are updated :)
Either way, thank you for your kind words again, we really appreciate such feedback!
